# Generated by Django 5.1.6 on 2025-03-10 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodeSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255)),
                ('language', models.CharField(max_length=50)),
                ('code', models.TextField()),
                ('output', models.TextField()),
                ('tab_switch_count', models.IntegerField(default=0)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
