# Generated by Django 5.1.6 on 2025-03-10 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compiler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.CharField(max_length=100, unique=True)),
                ('unlocked_levels', models.IntegerField(default=1)),
            ],
        ),
        migrations.DeleteModel(
            name='CodeSubmission',
        ),
    ]
